### PR TITLE
Proposal 308:Add rule ledger rule

### PR DESCRIPTION
**Pull request by rjulian**
I think it's kind of ambiguous how one goes about changing/amending rules. I enjoy a diff kind of setup with the rules, so that we can clearly see what previous versions were there and what has been added by players. 

I notice, this early on in the game, it's not exactly difficult, as we haven't played much. Additionally, we're putting this out there on a version control system, so you'd think this would be easier to see, but I really like the verbosity of showing everything in the file itself.

### CODE REVIEW

**Comment by audiodude** [comment]
omg you're insane.

**Comment by audiodude** [comment]
To clarify, I'm not completely against keeping a full record of rules in the rule file. But I _really_ don't like the +/- stuff. It seems like we're trying to replicate what git/github already gives us for free. What's the point? Just more administrative overhead. Also, if a rule contains:

Players may foo in the instance that a bar is present.

---

Players may only foo in the instance that a bar is present.

---

Players must foo, but only when one or more bars is present.

---

Then you have to read 3 rules just to find out that the latest one, that is in effect, is the last one. Why not just use Github history and comparison tools for that?

**Comment by sashahart** [comment]
I suppose this would only apply to subsequent proposals, otherwise it would be too difficult to implement and I would fear a game hang. Nicely done.

If this were a technique for tracking changes in code or something, I'd say it was crazy. But as a Nomic rule, that might be interesting. The way that the previous texts are all preserved in the present text, ready for reactivation, reminds me pleasingly of genetics and also gives sense to all that otherwise difficult text treating amendments specially. 

However, I still have a few reservations on behalf of my constituency. Therefore, I offer to trade a plus-vote for this measure in exchange for a vote on an upcoming proposal where every score is defined as a complex number having an imaginary part. (Rule 210 does not forbid this, as we are playing a game by computer, and 210 reads "The first paragraph of this rule does not apply to games by mail or computer." Rule 214 allows this because I am conveying my offer by Github, and this offer is pertinent to proposal 308 insofar as I am offering to ratify it.) Would you be open to that, rjulian?

**Comment by audiodude** [comment]
Like I said, I think keeping around past rules might work, but the plus minus stuff is a real bummer. Have you thought about what that looks like in practice?

Also I think it is a deficiency of our 3 player game that I would be rendered futile by the upcoming @rjulian / @sashahart  cabal. However I can only suggest that you play your cards carefully. What if I were to recruit two more players to my faction? The tables may turn quickly on your nascent political party.

**Comment by audiodude** [comment]
And also keep in mind @sashahart, that there is no rule that says @rjulian has to honor any such agreement. You could be betrayed before you know it, and we're all stuck with this crappy rule.

**Comment by rjulian** [comment]
So, I think this might've been pre-coffee Richard feeling a bit rushed to put out a proposal and not thinking it through completely.

I actually kind of agree with @audiodude about it getting tedious and a lot of redundancy with regards to maintaining each individual rule. 

That said, this may be a future proposal along these lines, but one of my biggest beefs is having to `cat` all of the individual files for one sentence. Why wouldn't we have two text files with two numbered lists mutable_rules and immutable_rules, so that at most, I would only have to scan two files to see all the rules. It's madness! A system of explicit + (addendum) and - (redaction) makes perfect sense in that system. 

On that note, I will completely be glad to offer up a vote for @sashahart in the future if she would like to trade me a vote. I imagine there will be an explanation for such a change, of which I look forward to!

**Comment by audiodude** [comment]
@rjulian you are free to vote against your own rule, since you seem to agree it's not a great idea.

Either way let me make it official:

-1

**Comment by sashahart** [comment]
@audiodude: I'm offering a one-off trade rather than a proposal of permanent alliance. I'm aware it's not enforceable by the rules, but in many ways the rules are not very reliable. I'll just have to rely on the logic of rational reciprocity. I vow to honor the deals I make, and if one doesn't work out then that is the cost of doing business and I just won't trust that person again. I am all in favor of further recruitment if anyone has a reason to do that. 

@rjulian: I'll +1 this once you +1 it so please make it exactly what you want it to be before giving your own +1. If you want just two text files I'll +1 anyway, but I will advise that merge conflicts could be a source of friction and are less likely by the current practice of having one rule per file. I think any of us could write a short script or maybe a shell one-liner to generate one or two files to read, but I'd be happy to PR a script by the administrative rule if it would be convenient.

edit: Also, not that this is important, but it happens I'm a dude (no offense taken), I was named after a dude named Sasha.

**Comment by audiodude** [comment]
As as point of procedure, the rules state in https://github.com/audiodude/odeon/blob/master/immutable_rules/111_Time-for-debate.md

> The proponent decides the final form in which the proposal is to be voted on and, unless the Judge has been asked to do so, also decides the time to end debate and vote.

In practice, it seems that we have all been deciding that the vote should be taken by each person adding +1/-1 whenever they feel like it, and then the proponent tallying and finalizing the vote by either closing or merging the pull request.

Either way, 111 does clearly state that players may propose amendments, but it must happen before the vote. So either my -1 is non-binding because we are not voting yet (unless @rjulian says we are), or we were already voting and the rule cannot be amended.

Also @rjulian is not required to proactively +1 via my just enacted rule 307: https://github.com/audiodude/odeon/blob/master/mutable_rules/307_Self-votes.md

**Comment by audiodude** [comment]
> edit: Also, not that this is important, but it happens I'm a dude (no offense taken), I was named after a dude named Sasha.

Also my next rule change is going to be "audiodude gets 10 points for not assuming the gender of @sashahart"  :)

**Comment by sashahart** [comment]
Apart from the rules, I was just saying that I will +1 if and when rjulian signals he's done, which he could do any time or not at all, at his option. The rules don't pertain to any of this, so it falls under 116 as "permitted and unregulated."

111 says that the proponent decides the time to end debate and vote, unless the Judge has been asked to do so. The Judge hasn't been asked to do so, so the proponent decides the time to end debate and vote. If we interpret the rules such that the first voter's vote decides the time to end debate, where the first voter is not necessarily the proponent, that is a contradiction with 111. Therefore I think the most natural interpretation is that audiodude's vote is not only non-binding but against the rules, unless rjulian as the proponent decides it came after the time to end debate and vote. Unfortunately there is really no defined way of dealing with things that happen against the rules, so I guess in practice we would just ignore it?

Per 212, audiodude could try to force the first-voter-decides interpretation by invoking Judgment, making audiodude the Judge. But rjulian and sashahart could potentially overrule the Judge, assuming there were no other players. Then the new Judge would have to be the player preceding audiodude in the turn order. This is a rule ambiguity, but I believe that would be sashahart, since I play the turns before audiodude's. I would insist on the plain reading of 111 given in the previous paragraph.

If the score were a complex number, I'd propose giving audiodude +10i for not assuming my gender, with the advantage that this would not affect the real part of audiodude's score.

**Comment by rjulian** [comment]
@sashahart Ugh, I tried sooooooo hard not writing gender pronouns (it's the internet, where we're all androids anyway), that one totally slipped. 

Okay, that said, I'm going to -1 my own proposal, as I have grown and been a better person and am ready to take the penalty of such. I'm still interested in the imaginary points we'll be receiving going forward. Sorry to waste ya'll's valuable reading time.

**Comment by rjulian** [comment]
Oooops, forgot to get your (presumably negative) vote @sashahart .

**Comment by sashahart** [comment]
-1

**Pull request closed without merging**
