### PR TITLE
Rule for passing turns

### PR DESCRIPTION
**Pull request by rjulian**
I'm out for the next week and a half, so I'm going to have to enter passing mode, whether it exists or not!

### CODE REVIEW

**Comment by audiodude** [comment]
I think I "know what you mean" on this one, but the language is not clear.

I think you need the following things:
1. What does passing/active actually mean? It seems you want us to infer from the names of the states, but since when do we infer things in Odeon? I would put a couple sentences comparing and contrasting these states, and explicitly stating that the turn of someone who is passing is, well, passed.
2. This rule conflicts with the rule on "turns cannot be passed", so I think that it needs explicit language around "This rule overrides rule 2xx".
3. This rule also conflicts with the rule on what pull requests are allowed, so it should note "For the purposes of rule 2xx, this is also an allowable Pull Request"

**Comment by audiodude** [comment]
Also, what are the relevant rules around passing/voting? Do players who are passing count as a vote for? a vote against? are they just not included and then a majority of 2 players means 1?

Thanks!

**Comment by sashahart** [comment]
I'm in favor of the idea.

**Comment by rjulian** [comment]
@audiodude @sashahart sorry about the slowdown on this. I'm now in stable internet lands and should be more able to communicate this.

**Comment by audiodude** [comment]
Made some comments about issues I still have, hopefully we can get things moving again?

**Comment by rjulian** [comment]
Good points, yet again sorry about the delay.

**Comment by rjulian** [comment]
I will cancel this proposal by Monday if no +1 vote has been received. I understand how long this is taking and am sorry.

**Comment by audiodude** [comment]
> I will cancel this proposal by Monday if no +1 vote has been received. I understand how long this is taking and am sorry.

No need to apologize, I wouldn't say it's your fault. Odeon proceeds at the rate it will.

**Comment by audiodude** [comment]
Also, I'm not sure you have the authority to "cancel" the rule change proposal. Rule 309 indicates that the proponent can close an accepted rule in the case it has enough votes. While it might "make sense" that the converse is true, that you can close when there are not enough votes for something to pass, that is not explicitly stated.

I think rule changes need everyone to vote in order to be defeated, so two -1s and one +1, or three -1s.

**Comment by rjulian** [comment]
Changed the diction on allowing auto merging of that passing pull request.

What I meant by cancel is I'd throw in the towel, vote -1 and tell you guys I won't do anything more with the proposal and you should just vote -1 as well.

**Comment by sashahart** [comment]
+1

I think this is pretty well cooked, but I will +1 any future PR as well

**Comment by audiodude** [comment]
I'm sorry, I just don't like the verbiage here, though I do like the basic idea.

-1

**Pull request merged**
