### PR TITLE
304: Change immutable rule 117 to mutable rule 304.

### PR DESCRIPTION
**Pull request by audiodude**
Obviously there is a bug in the rules, in that only the enumerated Pull Requests are allowed, yet we are required to keep the player files up to date with the score.

I have an idea for how to fix this, which I hinted at in a different PR, but it first requires that this rule be made mutable.

Remember, we would still have to vote on any proposed amendment or repeal.

Thanks!

### CODE REVIEW

**Comment by audiodude** [comment]
Oh and for completeness sake:

+1

**Comment by rjulian** [comment]
+1 definitely.

**Comment by sashahart** [comment]
+1

**Comment by audiodude** [comment]
304 Passes, 3 for, 0 against.

**Pull request merged**
