### PR TITLE
310: Transmute immutable rule 111 to be mutable rule 310.

### PR DESCRIPTION
**Pull request by audiodude**
I'd like to clarify the rules around debate and voting. Although we have established a system that works fairly well, in more heated debates I can definitely envision issues coming up.

Specifically, the rule here seems to imply that voting is a process that happens all at once, at the conclusion of amendment and debate. However, we have been conducting voting interleaved with amendment and debate.

Remember as always that a vote for this proposal simply transmutes the rule, it doesn't make any material changes yet.

Thanks!

### CODE REVIEW

**Comment by sashahart** [comment]
Yes, this is an important transmutation.

+1

(Intended interpretation: without implying that it is time to vote, whenever it will be time to vote, my vote will be +1. So I won't object if this comment functions as a +1 vote, and if it doesn't function as a +1 vote I will invoke judgment.)

**Comment by sashahart** [comment]
I'd like the amendments to specify more exactly in terms of syntax when a comment constitutes a vote. For example, a +1 vote has text beginning with +1, a -1 vote has text beginning with -1, nothing else constitutes a vote (so, for example, just talking about +1 does not constitute a vote unless the post begins with +1). This would make it more feasible to reliably automate vote counting, if for no other purpose than auditing the history.

I'd also like to fully specify whether or how people can rescind votes, since it is "physically" possible just to edit or delete a comment, how should or shouldn't that affect the rules. I don't like it, it troubles me. We can't prevent people from doing it, and a conflict with the rules is an invalid state or hang or something, so we have to know what happens in the rules when it happens in reality. I don't want this to constitute a "history edit" or to have race conditions of vote-removal against merge or whatever. (One thing I'm learning from this game is how awful the temporal aspect of lawmaking is)

I don't see need for more formal definition of the voting period than we have been using in practice. For example, I'm happy for the voting period to start from the public visibility of the PR, and extend to when either everyone has voted, or the proponent exercises the fast vote option (i.e., until the outcome is determinate). And I really don't see a problem about votes and comments (debate) intermingling: whenever it is time to count votes, just move through the comments tallying the votes. 

I do see a problem with pushing of changes to the PR branch after votes have happened, because obviously the vote was for a previous form. We could simply disallow pushing: the proposal is what it is, maybe next turn. I'd prefer that votes before a push were discounted, requiring explicit voting on the new form. For this it would also work to forbid votes until a declared time, and then forbid pushes after the declared time...

But here's what I really don't want: just after a PR is put up, nobody can vote, they are maybe only allowed to comment. (Assuming we can be generous enough to autostart discussion phase rather than requiring some formula to be said by proponent to start it.) Then I have to hold on to my vote. Then the proponent has to come in with some ceremonial declaration of end to debate, after which nobody is "allowed to" comment, so that when they do comment it can't just be ignored. And then maybe the proponent has to ceremonially declare the end of voting, but only if everyone voted. Every bit of this ceremony is going to become a gratuitous pain in the butt, and a place for a player to lag out.

I feel a proponent should reasonably be able to fire off a proposal, and if proponent wants to go to the beach for a few days without screwing things up, just +1 it pre-emptively and wander off without impeding the turn sequence.

**Comment by audiodude** [comment]
> I'd like the amendments to specify more exactly in terms of syntax when a comment constitutes a vote.

Totally agreed. I like something that includes "a vote counts if the +1/-1 is the last thing in the comment, on its own line". So you can do something like we've been doing: <wall of text> then blah blah. +1

> I'd also like to fully specify whether or how people can rescind votes, since it is "physically" possible just to edit or delete a comment

I agree again, I'd like to clarify the mechanism by which someone might change a vote. I think it might be worth its own rule that players should not (must not?) edit pull request comments after they have been made. Maybe you change your vote by entering a new vote, simple as that.

> I don't see need for more formal definition of the voting period than we have been using in practice......And I really don't see a problem about votes and comments (debate) intermingling: whenever it is time to count votes, just move through the comments tallying the votes.

I agree with you again. I think the system we have been using has been very workable and we should look to codify that system rather than come up with something else.

> I do see a problem with pushing of changes to the PR branch after votes have happened, because obviously the vote was for a previous form.

Once again, you're spot on. But I disagree that PR should be frozen and no one should be able to push commits to them. Maybe just the author of the PR/proposal should be able to make changes, and the other player's should be able to propose such changes/amendments.

I think it should be made explicit that when the PR changes, all votes are nullified and everyone has to vote again. You could make something "weaker" and just say that everyone has to "affirm their current vote" or something, but honestly that seems to be fundamentally the same as just voting again.

> But here's what I really don't want....

Again, I am in agreement. Like I said, we should codify what we have and not try to add any pomp and circumstance.

**Comment by sashahart** [comment]
For sure you should write this however you want, I'm just talking here because the new thing isn't around yet.

Syntax: last line for the +1/-1 is a nice way of wrapping up existing practice.

Vote changes: it's cool to let people change their vote by entering a new vote. 

We then have to decide a point where we are no longer waiting for further appends to the vote stream. A couple options: maybe (A) vote-changes after the point of sufficiency to decide outcome do not count, or (B) votes after a merge is done according to the rules do not count. Alternatively, (C) special ceremony to end voting marks the end time explicitly. I favor (A) and dislike (C).

My deeper concern is the headache when users post vote comments, then delete them. Edits not affecting votes are fine. The first impulse will be to enact rules saying "must not edit votes," but then the rules cannot handle situations where people actually did so, and we can't prevent this from happening, so the game state is invalid. To avoid that, I want the rules to see history as immutable: your moves in the game (in this case, votes) can never be un-made, and deleting the record doesn't change that in terms of the rules. We can use whatever practical mechanisms we want to preserve evidence of history, or argue about history. (This is really very similar to our earlier discussion about scores: it's not that I want people to delete their votes, but I just don't want the rules to recognize the deletion as meaning anything if the "move" was already made.)

Pushes: I think we agree that freezing PRs seems undesirable and that the best option is that a push invalidates votes, requiring everyone to vote again.

**Comment by rjulian** [comment]
Transmutate, baby. +1

**Pull request merged**
