### PR TITLE
301: Transumte rule 105 to be mutable.

### PR DESCRIPTION
**Pull request by audiodude**
Greetings @rjulian and @sashahart and welcome to Odeon! This Pull Request represents the first move of the first round. It is my (@audiodude) turn, as I have the lowest player number.

I have noticed some inconsistencies in the rules and would like to set about fixing them straightaway. To this end, I'd like to make this rule mutable so that it can be amended (somehow?) to not require every single player in the game to vote on every rule-change. Specifically, the intention was that only those players that were "in" a round should be required to vote. And it may be necessary to require some concept of "quorum" so that only active players are required to vote on a rule change.

### CODE REVIEW

**Comment by sashahart** [comment]
+1

**Comment by audiodude** [comment]
+1

(As stated the rules don't make it clear that you automatically vote for your own rule change: fodder for potential rule changes in the future)

**Comment by rjulian** [comment]
-1 This seems like a pretty integral rule that doesn't need to be mutable. How do you do scoring if you not all voters have to vote (do you assume not cast votes are not in favor, in favor, etc?). Additionally, we've capped this game at so few players. Sorry, I don't think this rule needs to be mutable!

**Comment by audiodude** [comment]
301 fails, 2 in favor, 1 against.

I should get 7 points via https://github.com/audiodude/odeon/blob/master/mutable_rules/202_Parts-of-a-turn.md

But unfortunately, https://github.com/audiodude/odeon/blob/master/immutable_rules/117_Github-repository.md doesn't allow for the repo to be changed to reflect scores!

**Comment by rjulian** [comment]
Shouldn't you get -10 via https://github.com/audiodude/odeon/blob/master/mutable_rules/206_Defeated-proposals.md?

**Comment by audiodude** [comment]
We're both right. The computer game equivalent of rolling a die gives me 7 (https://github.com/audiodude/odeon/blob/master/mutable_rules/202_Parts-of-a-turn.md) and the rule you stated gives me -10, so I end up with -3.

The real problem is that while https://github.com/audiodude/odeon/blob/master/immutable_rules/118_Players-and-joining-the-game.md
dictates that my score file should now contain -3, https://github.com/audiodude/odeon/blob/master/immutable_rules/117_Github-repository.md dictates that no commit be made to the master branch except by PR and that changing scores is not a valid PR (an oversight to be certain).

It seems the workaround is to change scores via the "administrative" PR for now until rule 117 can be mutated and amended.

**Comment by sashahart** [comment]
I believe the game is hung by the violation of rule 118: actual scores are changing while player files are not. So in the interests of continuing play, I will give my approval vote to all playerfile-score change PRs citing the authority of rule 117 point 6 until this issue with rule 117 is fixed.

It is for the same reason (concern about game hangs) that I will +1 transmutation of 105 so that it can be fixed: as the game goes on and players are added, the probability that someone will idle out and not vote increases, and by 105 this will hang the game indefinitely when it does happen. This is regardless of whether 302 (amending 203) simplifies the criterion for deciding the vote outcome.

**Comment by audiodude** [comment]
So if 302 (#6)  passes, I think we can transmute 105 by majority rule either on your turn @sashahart or on my following turn next round.

I'll create the score change PR now.

**Pull request closed without merging**
