### PR TITLE
313: New rule, Robin Hood.

### PR DESCRIPTION
**Pull request by audiodude**
It should be self apparent: rob from the rich, give to everybody else! I originally had it as five points, but it didn't feel like it had teeth really. But I'm willing to negotiate the magnitude.

### CODE REVIEW

**Comment by sashahart** [comment]
Yes, but what about the incentive to innovate? Self-determination? Job creators?

Actually, the only reason I haven't voluntarily redistributed points already to the players of my choosing is because I don't have a mechanism to do it. Why not put one in? This government is suppressing a potentially thriving points economy. 

The least you could do is compensate me with imaginary points equal to the real points lost, they're just imaginary anyway and I can use them to remember the real points I used to have, when I am old. 

You could also remove the entire paragraph about complex numbers because the clear meaning is already that the "rich" loses (10 + 0i) \* n and the "poor" gain 10 + 0i each. If you are trying to remove imaginary points as well, that is ambiguous at best in the current form

**Comment by audiodude** [comment]
Yes the part about dealing with complex numbers was put in hastily at best. But the thing I don't understand is, are there implicit methods of comparison for complex numbers? If you have 10 + 1000i points, do you have more or less points than someone who has 10 + 100i? What about someone who hast 9 + 10000i? This is what I was talking about with 312 introducing a lot of math.

Otherwise, I like the changes you suggest, and I will attempt to make them.

**Comment by rjulian** [comment]
Hmmm.. while I'd prefer to have this go to the poor, I'm always in favor of mindless wealth distribution. 

Down with the point rich of this game! +1!

**Comment by audiodude** [comment]
I am invoking summary closure per rule 309.

**Pull request merged**
