### PR TITLE
302: Amend 203 to need only simple majority

### PR DESCRIPTION
**Pull request by rjulian**
I've been thinking: two full rounds is way too long to wait for non-unanimous voting.

I propose to amend [Rule 203](https://github.com/audiodude/odeon/blob/master/mutable_rules/203_Rule-changes-unanimous-at-first.md) to only require a simple majority, rather than unanimous voting. This is for the sanctity of our precious union and to empower the voice of the people in this here forum of discussion. Good luck, god speed.

### CODE REVIEW

**Comment by audiodude** [comment]
I agree with this in principle. However https://github.com/audiodude/odeon/blob/master/immutable_rules/108_Numbering-rules.md states:

> If a rule is amended or transmuted, it receives the number of the proposal to amend or transmute it.

So you should also rename the file from 203 to 302, which is kind of funny.

**Comment by rjulian** [comment]
Fixed, I was wondering about that. You +1?

**Comment by audiodude** [comment]
+1

**Comment by sashahart** [comment]
+1

**Comment by audiodude** [comment]
302 passes, 3 for, 0 against.

I believe @rjulian's score should be 11 (302-291 \* 3/3). I can make an administrative PR to update it.

It is now @sashahart's turn.

**Comment by audiodude** [comment]
Oh crap, I take that back. Like I said before, it's not explicit that you vote for your own rule changes, so technically @rjulian has to vote...

**Comment by sashahart** [comment]
I am making a PR for my coming turn, but play can't advance until we finish rjulian's turn properly.

**Comment by rjulian** [comment]
+1

**Pull request merged**
